name: Base-Network

on:
  push:
    branches:
      - "Base-Network-Deployment"

env:
  location: 'eastus'
  AZURE_RESOURCE_GROUP: 'rg_bicep_test'

jobs:
  AzureBicepDeploy:
    name: 'AzureBicepDeploy'
    runs-on: ubuntu-latest
 
    steps:
    -  name: Checkout Code
       uses: actions/checkout@v2

    -  name: Build ARM
       run: |
         az bicep build --file ../../AzureCloud/Root-MG/Sub1/rg_bicep_test/networkdeploy.bicep

    -  name: Azure Login
       uses: azure/login@v1
       with:
         creds: ${{ secrets.AZURE_CREDENTIALS }}

    -  name: Deploy template
       uses: azure/CLI@v1
       with:
         inlineScript: |
           az account show
           az deployment group create -f ./networkdeploy.json -g ${{ env.AZURE_RESOURCE_GROUP }}
   