name: ManagementGroups

on: push

env:
  location: 'eastus' 
  rootMg: 'Tenant Root Group'

jobs:
  AzureBicepDeploy:
    name: 'AzureBicepDeploy'
    runs-on: ubuntu-latest
 
    steps:
    -  name: Checkout Code
       uses: actions/checkout@v2

    # -  name: Build Management Group 
    #    run: |
    #      az bicep build --file AzureCloud/Root-MG/Root-MG-Test.bicep

    -  name: Azure Login
       uses: azure/actions/login@v1
       with:
         creds: ${{ secrets.MSDN_SECRET }}

    -  name: Deploy CAF
       uses: azure/powershell@v1
       with:
         inlineScript: |
           New-AzTenantDeployment -TemplateFile Standard-Deployments/CAF-Landing-Zone-MG/caf-mg-deploy.bicep -TemplateParameterFile Standard-Deployments/CAF-Landing-Zone-MG/parameters.json -Location ${{ env.location }}
          azPSVersion: "latest"